"""Order payment id

Revision ID: 0773d0c62142
Revises: 746cb2239ed3
Create Date: 2020-08-28 14:14:49.728068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0773d0c62142'
down_revision = '746cb2239ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_id')
    # ### end Alembic commands ###
