"""Order shipping type/time

Revision ID: 2fb2bdf8e153
Revises: 4ea9575e03f5
Create Date: 2020-09-10 12:20:49.118878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb2bdf8e153'
down_revision = '4ea9575e03f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_time', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('shipping_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_type')
    op.drop_column('order', 'shipping_time')
    # ### end Alembic commands ###
