"""Order payment type and paid

Revision ID: 4ea9575e03f5
Revises: 0773d0c62142
Create Date: 2020-09-01 13:04:09.624962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea9575e03f5'
down_revision = '0773d0c62142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('payment_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_type')
    op.drop_column('order', 'paid')
    # ### end Alembic commands ###
