"""Billing/shipping information

Revision ID: 51d396df864b
Revises: 47c8385e834c
Create Date: 2020-08-24 19:08:27.417728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d396df864b'
down_revision = '47c8385e834c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('address_1', sa.String(length=200), nullable=False),
    sa.Column('address_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.Column('card', sa.String(length=200), nullable=True),
    sa.Column('expiration', sa.String(length=10), nullable=True),
    sa.Column('cvc', sa.String(length=10), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('shipping_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'information', ['billing_id'], ['id'])
    op.create_foreign_key(None, 'order', 'information', ['shipping_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shipping_id')
    op.drop_column('order', 'billing_id')
    op.drop_table('information')
    # ### end Alembic commands ###
