"""User phone and company

Revision ID: 746cb2239ed3
Revises: 51d396df864b
Create Date: 2020-08-26 09:49:24.004902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746cb2239ed3'
down_revision = '51d396df864b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'company')
    # ### end Alembic commands ###
