"""Product options

Revision ID: bfd9c8ebec44
Revises: 51789b48ebd8
Create Date: 2020-08-21 21:13:38.504418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfd9c8ebec44'
down_revision = '51789b48ebd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('item', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('product', 'available')
    op.drop_column('product', 'price')
    op.drop_column('product', 'sale_price')
    op.drop_column('product', 'notes')
    op.drop_column('product', 'packaging')
    op.drop_column('product', 'barcode')
    op.drop_column('product', 'comment')
    op.drop_column('product', 'location')
    op.drop_column('product', 'capacity')
    op.drop_column('product', 'on_sale')
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('product', sa.Column('on_sale', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('product', sa.Column('comment', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('product', sa.Column('barcode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('product', sa.Column('packaging', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('product', sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('product', sa.Column('sale_price', mysql.FLOAT(), nullable=True))
    op.add_column('product', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.add_column('product', sa.Column('available', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('item', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('item', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
