"""Billing/Shipping Information

Revision ID: d83b50dfadb0
Revises: 47c8385e834c
Create Date: 2020-08-24 15:16:30.056407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b50dfadb0'
down_revision = '47c8385e834c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('information', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('shipping_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'information', ['shipping_id'], ['id'])
    op.create_foreign_key(None, 'order', 'information', ['billing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shipping_id')
    op.drop_column('order', 'billing_id')
    op.drop_column('information', 'updated')
    op.drop_column('information', 'created')
    # ### end Alembic commands ###
