"""Category image

Revision ID: e8ac322628ea
Revises: 7c29a8618203
Create Date: 2020-08-20 11:14:15.158523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ac322628ea'
down_revision = '7c29a8618203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image_path')
    # ### end Alembic commands ###
