"""Page top_nav

Revision ID: f5c57a6813ac
Revises: e8ac322628ea
Create Date: 2020-08-21 13:06:59.903332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c57a6813ac'
down_revision = 'e8ac322628ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('top_nav', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'top_nav')
    # ### end Alembic commands ###
